name: "Github Actions Test"
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: "Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: "npm install"
        run: npm install
      - name: "Start server, and run newman"
        run: |
          npm start &
          sleep 10
          npm run newman